on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: PHP Integration (Keycloak compatibility)

jobs:
  Integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        keycloak: [ 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 22.0.0, 22.0.5, 23.0.0, 24.0.0, 25.0.0, 26.0.0, 26.0.5 ]
        php: [ 8.1 ]

    env:
      KEYCLOAK_VERSION: ${{ matrix.keycloak }}
      KEYCLOAK_BASE_URL: 'http://localhost:8080'
      XDEBUG_MODE: coverage

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Start Keycloak container
        run: >
          docker run -d
          -p 8080:8080
          -e KEYCLOAK_ADMIN=admin
          -e KEYCLOAK_ADMIN_PASSWORD=admin
          --name keycloak
          quay.io/keycloak/keycloak:${{ matrix.keycloak }}
          start-dev

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Wait for Keycloak
        uses: iFaxity/wait-on-action@v1
        with:
          resource: http-get://localhost:8080
          timeout: 30000

      - name: Wait some more for Keycloak 24.0.0 zZz
        if: ${{ matrix.keycloak == '24.0.0' }}
        run: sleep 5

      - name: Run integration tests
        run: vendor/bin/phpunit --testsuite integration
